---
name: Build

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '30 13 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest

    steps:
    - name: Download deps
      shell: bash
      run: |
        if [[ ${RUNNER_OS} == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y lib{pango1.0,x11,xext,xft,xinerama,mpv}-dev\
                lib{xcursor,xrender,xfixes,webkit2gtk-4.1,vlc,png,gl1-mesa}-dev\
                ninja-build libglu1-mesa-dev
        fi
    - uses: actions/checkout@v2
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: build cfltk
      run: |
        git clone https://github.com/MoAlyousef/cfltk
        pushd cfltk || return 1
        git submodule update --init --recursive
        case ${RUNNER_OS} in
            Linux ) cmake -Bbin -GNinja -DFLTK_USE_SYSTEM_LIBPNG=OFF -DFLTK_USE_SYSTEM_LIBJPEG=OFF -DFLTK_USE_SYSTEM_ZLIB=OFF -DCFLTK_LINK_IMAGES=ON -DOpenGL_GL_PREFERENCE=GLVND -DFLTK_BUILD_GL=ON -DCFLTK_USE_OPENGL=ON -DCFLTK_SINGLE_THREADED=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCFLTK_CARGO_BUILD=ON -DFLTK_BUILD_EXAMPLES=OFF -DFLTK_BUILD_TEST=OFF -DFLTK_OPTION_LARGE_FILE=ON -DFLTK_BUILD_HTML_DOCS=OFF -DFLTK_BUILD_PDF_DOCS=OFF -DCMAKE_INSTALL_PREFIX=bin -DCMAKE_BUILD_TYPE=Release -DFLTK_GRAPHICS_CAIRO=ON -DFLTK_USE_PANGO=ON -DFLTK_BACKEND_WAYLAND=OFF;;
            macOS ) cmake -Bbin -GNinja -DFLTK_USE_SYSTEM_LIBPNG=OFF -DFLTK_USE_SYSTEM_LIBJPEG=OFF -DFLTK_USE_SYSTEM_ZLIB=OFF -DCFLTK_LINK_IMAGES=ON -DOpenGL_GL_PREFERENCE=GLVND -DFLTK_BUILD_GL=ON -DCFLTK_USE_OPENGL=ON -DCFLTK_SINGLE_THREADED=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCFLTK_CARGO_BUILD=ON -DFLTK_BUILD_EXAMPLES=OFF -DFLTK_BUILD_TEST=OFF -DFLTK_OPTION_LARGE_FILE=ON -DFLTK_BUILD_HTML_DOCS=OFF -DFLTK_BUILD_PDF_DOCS=OFF -DCMAKE_INSTALL_PREFIX=bin -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES=x86_64;;
            * )     cmake -Bbin -GNinja -DFLTK_USE_SYSTEM_LIBPNG=OFF -DFLTK_USE_SYSTEM_LIBJPEG=OFF -DFLTK_USE_SYSTEM_ZLIB=OFF -DCFLTK_LINK_IMAGES=ON -DOpenGL_GL_PREFERENCE=GLVND -DFLTK_BUILD_GL=ON -DCFLTK_USE_OPENGL=ON -DCFLTK_SINGLE_THREADED=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCFLTK_CARGO_BUILD=ON -DFLTK_BUILD_EXAMPLES=OFF -DFLTK_BUILD_TEST=OFF -DFLTK_OPTION_LARGE_FILE=ON -DFLTK_BUILD_HTML_DOCS=OFF -DFLTK_BUILD_PDF_DOCS=OFF -DCMAKE_INSTALL_PREFIX=bin -DCMAKE_BUILD_TYPE=Release;;
        esac
        cmake --build bin --parallel --target install
        export CFLTK_BUNDLE_DIR="${PWD}/bin/lib"
      shell: bash
    - name: Build cairo
      working-directory: cairo
      shell: bash
      run: |
        if [[ ${RUNNER_OS} == "Linux" ]]; then
            cargo build --quiet || cargo build --verbose
        fi
    - name: Build cairo_shadow_button
      working-directory: cairo_shadow_button
      shell: bash
      run: |
        if [[ ${RUNNER_OS} == "Linux" ]]; then
            cargo build --quiet || cargo build --verbose
        fi
    - name: Build calculator
      working-directory: calculator
      shell: bash
      run: |
        cargo build --quiet || cargo build --verbose
    - name: Build calendar
      working-directory: calendar
      shell: bash
      run: |
        cargo build --quiet || cargo build --verbose
    - name: Build csv
      working-directory: csv
      shell: bash
      run: |
        cargo build --quiet || cargo build --verbose
    - name: Build egui
      working-directory: egui
      shell: bash
      run: |
        cargo build --quiet || cargo build --verbose
    - name: Build femtovg
      working-directory: femtovg
      shell: bash
      run: |
        cargo build --quiet || cargo build --verbose
    - name: Build ffmpeg
      working-directory: ffmpeg
      shell: bash
      run: |
        case ${RUNNER_OS} in
            Linux | macOS) cargo build --quiet || cargo build --verbose;;
        esac
    - name: Build dialect
      working-directory: dialect
      shell: bash
      run: |
        cargo build --quiet || cargo build --verbose
    - name: Build flmusic
      working-directory: flmusic
      shell: bash
      run: |
        case ${RUNNER_OS} in
            Linux | macOS) cargo build --quiet || cargo build --verbose;;
        esac
    - name: Build picture
      working-directory: picture
      shell: bash
      run: |
        cargo build --quiet || cargo build --verbose
    - name: Build resters
      working-directory: resters
      shell: bash
      run: |
        cargo build --quiet || cargo build --verbose
    - name: Build fltext
      working-directory: fltext
      shell: bash
      run: |
        cargo build --quiet || cargo build --verbose
    - name: Build framebuffer
      working-directory: framebuffer
      shell: bash
      run: |
        cargo build --quiet || cargo build --verbose
    - name: Build glium
      working-directory: glium
      shell: bash
      run: |
        cargo build --quiet || cargo build --verbose
    - name: Build glow
      working-directory: glow
      shell: bash
      run: |
        cargo build --quiet || cargo build --verbose
    - name: Build glut
      working-directory: glut
      shell: bash
      run: |
        cargo build --quiet || cargo build --verbose
    - name: Build image
      working-directory: image
      shell: bash
      run: |
        cargo build --quiet || cargo build --verbose
    - name: Build inner
      working-directory: inner
      shell: bash
      run: |
        if [[ ${RUNNER_OS} == "Linux" ]]; then
          cargo build --quiet || cargo build --verbose
        fi
    - name: Build libvlc
      working-directory: libvlc
      shell: bash
      run: |
        if [[ ${RUNNER_OS} == "Linux" ]]; then
          cargo build --quiet || cargo build --verbose
        fi
    - name: Build mpv
      working-directory: mpv
      shell: bash
      run: |
        if [[ ${RUNNER_OS} == "Linux" ]]; then
            cargo build --quiet || cargo build --verbose
        fi
    - name: Build musicplayer
      working-directory: musicplayer
      shell: bash
      run: |
        cargo build --quiet || cargo build --verbose
    - name: Build opengl
      working-directory: opengl
      shell: bash
      run: |
        cargo build --quiet || cargo build --verbose
    - name: Build pixels
      working-directory: pixels
      shell: bash
      run: |
        cargo build --quiet || cargo build --verbose
    - name: Build plotters
      working-directory: plotters
      shell: bash
      run: |
        cargo build --quiet || cargo build --verbose
    - name: Build raqote
      working-directory: raqote
      shell: bash
      run: |
        cargo build --quiet || cargo build --verbose
    - name: Build rounded-svg
      working-directory: rounded-svg
      shell: bash
      run: |
        cargo build --quiet || cargo build --verbose
    - name: Build speedy2d
      working-directory: speedy2d
      shell: bash
      run: |
        cargo build --quiet || cargo build --verbose
    - name: Build systray
      working-directory: systray
      shell: bash
      run: |
        if [[ ${RUNNER_OS} == "Windows" ]]; then
            cargo build --quiet || cargo build --verbose
        fi
    - name: Build terminal
      working-directory: terminal
      shell: bash
      run: |
        cargo build --quiet || cargo build --verbose
    - name: Build tinyskia
      working-directory: tinyskia
      shell: bash
      run: |
        cargo build --quiet || cargo build --verbose
    - name: Build web-todo
      working-directory: web-todo
      shell: bash
      run: |
        cargo build --quiet || cargo build --verbose
    - name: Build web-todo2
      working-directory: web-todo2
      shell: bash
      run: |
        cargo build --quiet || cargo build --verbose
    - name: Build webview
      working-directory: webview
      shell: bash
      run: |
        if [[ ${RUNNER_OS} == "Linux" ]]; then
            cargo build --quiet || cargo build --verbose
        fi
    - name: Build xterm
      working-directory: xterm
      shell: bash
      run: |
        if [[ ${RUNNER_OS} == "Linux" ]]; then
            cargo build --quiet || cargo build --verbose
        fi
    - name: Build wgpu
      working-directory: wgpu
      shell: bash
      run: |
        cargo build --quiet || cargo build --verbose
